logging:
  level:
    event:
      event_microservice:
        clients.*: DEBUG

spring:
  output:
    ansi:
      enabled: always
  application:
    name: event-microservice
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

email-service-client:
  name: email-sender

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true